julu-deploy:
  global:
    releaseVersion: "1"
    env: prod
    juluAppName: "exp"
    ddServiceName: "exp-ui"
    reCreatePod:
      enabled: true
    image:
      name: exp-ui
      tag: 268.2.7
      registry: xyz.azurecr.io
    minReplicas: 2
    maxReplicas: 8
  appCommands:
    - /bin/sh
    - sleep 50s
