julu-deploy:
  global:
    releaseVersion: "1"
    env: prod
    juluAppName: "exp"
    ddServiceName: "exp-ui"
    reCreatePod:
      enabled: true
    image:
      name: exp-ui
      tag: 1.2.9
      registry: xyz.azurecr.io
    minReplicas: 2
    maxReplicas: 8
