julu-deploy:
  env:
    # -- Environment for the application
    prouat
  region:
    dnsZone: "azure-julu-np.net.com.eu"
    app: 12.5.12
    version: 5.7.9 # -- Application name updated
    appName: Appname-version.1
  # -- Application name
  appName: commitapp
  podResources:
    requests:
      cpu: 8
  secrets:
    - secret: mySecret
