julu-deploy:
  env:
    # -- Environment for the application
    uat
  region:
    dnsZone: "azure-julu-np.net.com.eu"
    app: 12.5.12
    version: 5.7.9 # -- Application name updated
    appName: mynewapp
  # -- Application name
  appName: commitapp
  podResources:
    requests:
      cpu: 8
