julu-deploy:
  env: prod
  dnsZone: ""
  region:
    - europe:
        dns: ""
    
  app: mytestapp
  version: 265.2.9
  domainPrefix: mytestapp
  cNamePath: /(.*)
  servicePort: 8000
  customNginxAnnotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "240"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "240"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "240"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
  tls:
    enabled: true
