julu-cname:
  env:
    # -- Environment for the application
    - uat
  region:
    dnsZone: "azure-julu-np.net.com.eu"
    app: juluapp
    version: 5.7.9
      # -- Application name updated
      appName: Appname-version.1
