name: script-executor


on:
  workflow_dispatch:
    inputs:
      Select:
        description: "Provide Scripts which need to be ignored during execution"
        type: boolean
        default: false
      Preview:
        description: "scipt"
        type: boolean
        default: false
      Preview_2:
        description: "scipt_2"
        type: boolean
        default: false  
jobs:
      
  Select:
    if: inputs.Select && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.MYSECRET }}
      - name: echo
        run:  |
          exit 1


  Preview_step1:
    needs:  [ Select]
    if: inputs.Preview && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: check
        run:  |
          if [[ needs.Select.result == 'skipped' ]]; then
            echo "The job 'Select' is skipped"
            exit 0
          else 
            echo "continuing with current job"
          fi  
      - name: echo
        run:  |
          exit  0
  Preview_step2:
    needs:  [ Preview_step1]
    if: inputs.Preview_2 && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: check
        run:  |
          if [[ needs.Preview_step1.result == 'skipped' ]]; then
            echo "The job 'Preview_step1' is  skipped"
            exit 0
          else 
            echo "continuing with current job"
          fi  
      - name: echo
        run:  |
             if [[ (inputs.Preview_2 && (needs.Preview_step1.result == 'success' )) && !cancelled()   ]]; then
               echo "bagha"
             else
               echo "false bagha"
             fi  
             echo "${{ inputs.Preview_2}}"
             echo "${{ needs.Preview_step1.result == 'success'}}"
             echo "${{ needs.Preview_step1.result == 'skipped' }}"
             echo "${{ needs.Preview_step1.result == 'failure' }}"

             
  mail_success:
    needs: [Select,Preview_step1,Preview_step2]
    runs-on: ubuntu-latest
    if:  |
        (needs.Select.result == 'success' || needs.Select.result == 'skipped') &&
        (needs.Preview_step1.result == 'success' || needs.Preview_step1.result == 'skipped') &&
        (needs.Preview_step2.result == 'success' || needs.Preview_step2.result == 'skipped') && !cancelled()
    steps:
      - name: echo new
        run:  |
          echo new
  mail_failure:
    needs: [Preview_step1,Select,Preview_step2]
    runs-on: ubuntu-latest
    if: failure() || cancelled()
    steps:
      - name: echo mail
        run:  |
          echo "sending mail"          
