name: Add Yaml

run-name: Add Yaml - ${{ inputs.yaml || inputs.custom_yaml || inputs.value_yaml }}

on:
  workflow_dispatch:
    inputs:
      yaml:
        type: string
        description: Provide Yaml structure to be add , Please note top hierchy is set as niq-deploy
      custom_yaml:
        type: string
        description: Provide your custom structure
      value_yaml:
        type: string
        description: Provide a value which you want to override in yaml file
      files:
        type: choice
        description: structure/value to be added to yaml file
        options:
          - 'usuat'
          - 'euuat'
          - 'euuat,usuat'
          - 'ushofix'
          - 'usprod,euprod'
          - 'calatamprod,apacprod'
          - 'usprod,euprod,calatamprod,apacprod'
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

  Node:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6

  Script:
   runs-on: ubuntu-latest
   needs: Node
   steps:
     - name: Run script
       run:  |
         ls -a
         pwd
         IFS=',' read -ra envArray <<< "${{ inputs.files }}"
         echo "envArray=$envArray" >> $GITHUB_ENV
         npm install yaml
         node myfile.js
         
   
      
  
  
  
      
